name: GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      API_KEY: ${{ secrets.API_KEY }}

    steps:
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.1

      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
  
      - name: Install
        run: rm -rf node_modules && yarn install --frozen-lockfile
        working-directory: ./app

      - name: CMS
        run: yarn cms
        working-directory: ./app

      - name: Build
        run: yarn build
        working-directory: ./app
        
      - name: Export
        run: yarn export
        working-directory: ./app
        
      - name: Add nojekyll
        run: touch ./app/out/.nojekyll
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./app/out